flowchart LR

0[".dependency-cruiser.js"]
subgraph 1["application"]
subgraph 2["boardgame"]
3["AddBoardGameToUser.ts"]
4["DeleteBoardGame.ts"]
5["FindBoardGame.ts"]
6["GetBoardGame.ts"]
7["GetUserGameCollection.ts"]
end
subgraph 8["friendships"]
9["AcceptRequest.ts"]
A["AddFriend.ts"]
B["DeclineRequest.ts"]
C["GetFriendRequests.ts"]
D["GetFriends.ts"]
E["InviteFriend.ts"]
end
subgraph F["location"]
G["CreateLocation.ts"]
J["FindLocationById.ts"]
end
subgraph K["session"]
L["AddLocationToSession.ts"]
N["CreateSession.ts"]
O["GetGameSessions.ts"]
P["GetSessionById.ts"]
Q["GetSessionsByUserId.ts"]
R["findByGroupID.ts"]
S["updateSession.ts"]
end
subgraph T["sessionPlayer"]
U["findBySessionAndUser.ts"]
V["findBySessionID.ts"]
W["findByUserID.ts"]
X["saveSessionPlayer.ts"]
end
subgraph Y["user"]
Z["AddAvatar.ts"]
10["AddFavoriteLocation.ts"]
11["ChangeNickname.ts"]
12["CreateUser.ts"]
14["DeleteUser.ts"]
15["FetchUserNickname.ts"]
16["GetFavoriteLocations.ts"]
17["ValidateNickname.ts"]
end
end
subgraph H["domain"]
I["Location.ts"]
M["Session.ts"]
13["User.ts"]
1D["BoardGame.ts"]
1J["Friendship.ts"]
1S["SessionPlayer.ts"]
1X["Group.ts"]
1Y["UserBoardGames.ts"]
end
subgraph 18["composition"]
19["boardGame.ts"]
1H["friendships.ts"]
1L["location.ts"]
1N["session.ts"]
1Q["sessionPlayer.ts"]
1U["user.ts"]
end
subgraph 1A["infrastructure"]
subgraph 1B["postgres"]
1C["BoardGameRepository.ts"]
1G["db.ts"]
1I["FriendRepository.ts"]
1M["LocationRepository.ts"]
1O["SessionRepository.ts"]
1R["SessionPlayerRepository.ts"]
1V["UserRepository.ts"]
end
subgraph 1Z["InMemory"]
20["BoardGameRepository.ts"]
23["FriendRepository.ts"]
24["LocationRepository.ts"]
25["SessionPlayerRepository.ts"]
26["SessionRepository.ts"]
27["UserRepository.ts"]
end
subgraph 28["bgg"]
29["BggXmlApi2Client.ts"]
2A["bggSyncWorker.ts"]
end
end
subgraph 1E["ports"]
1F["BoardGameRepository.ts"]
1K["FriendRepository.ts"]
1P["SessionRepository.ts"]
1T["SessionPlayerRepository.ts"]
1W["UserRepository.ts"]
3E["LocationRepository.ts"]
end
21["fs"]
22["path"]
subgraph 2B["interfaces"]
subgraph 2C["http"]
subgraph 2D["controllers"]
2E["acceptRequestController.ts"]
2F["addAvatarController.ts"]
2G["addBoardGameToUserController.ts"]
2H["addFavoriteLocationController.ts"]
2I["addFriendController.ts"]
2J["addLocationToSessionController.ts"]
2K["createSessionController.ts"]
2L["createUserController.ts"]
2M["declineFriendRequestController.ts"]
2N["deleteBoardGameController.ts"]
2O["deleteUserController.ts"]
2P["fetchUserNicknameController.ts"]
2Q["findBoardGameController.ts"]
2R["getBoardGameController.ts"]
2S["getFavoriteLocationsController.ts"]
2T["getFriendRequestsController.ts"]
2U["getFriendsController.ts"]
2V["getSessionByIdController.ts"]
2W["getSessionController.ts"]
2X["getSessionsByUserIdController.ts"]
2Y["getUserGameCollectionController.ts"]
2Z["inviteFriendController.ts"]
30["saveSessionPlayerController.ts"]
31["updateNicknameController.ts"]
32["updateSessionController.ts"]
33["validateNicknameController.ts"]
end
subgraph 34["middleware"]
35["auth.ts"]
36["uploadAvatar.ts"]
end
subgraph 37["routes"]
38["boardgames.ts"]
39["friendships.ts"]
3A["sessionPlayers.ts"]
3B["sessions.ts"]
3C["users.ts"]
end
3D["server.ts"]
end
end
3F["server.ts"]
subgraph 3G["tests"]
3H["dbTest.js"]
end
G-->I
L-->I
L-->M
N-->I
S-->M
12-->13
19-->3
19-->4
19-->5
19-->6
19-->7
19-->1C
19-->1G
1C-->1D
1C-->1F
1H-->9
1H-->A
1H-->B
1H-->C
1H-->D
1H-->E
1H-->1G
1H-->1I
1I-->1J
1I-->1K
1L-->G
1L-->J
1L-->1G
1L-->1M
1M-->I
1N-->L
1N-->N
1N-->O
1N-->P
1N-->Q
1N-->S
1N-->1G
1N-->1M
1N-->1O
1O-->M
1O-->1P
1Q-->U
1Q-->V
1Q-->W
1Q-->X
1Q-->1G
1Q-->1R
1R-->1S
1R-->1T
1U-->Z
1U-->10
1U-->11
1U-->12
1U-->14
1U-->15
1U-->16
1U-->17
1U-->1G
1U-->1V
1V-->I
1V-->13
1V-->1W
20-->1F
20-->21
20-->22
24-->I
25-->1T
26-->M
26-->1P
27-->I
27-->13
27-->1W
2A-->29
2F-->21
2F-->22
36-->21
36-->22
38-->2G
38-->2N
38-->2Q
38-->2R
38-->2Y
38-->35
39-->2E
39-->2I
39-->2M
39-->2T
39-->2U
39-->2Z
39-->35
3A-->30
3B-->2J
3B-->2K
3B-->2V
3B-->2W
3B-->2X
3B-->32
3B-->35
3C-->2F
3C-->2H
3C-->2L
3C-->2O
3C-->2P
3C-->2S
3C-->31
3C-->33
3C-->35
3D-->35
3D-->38
3D-->39
3D-->3A
3D-->3B
3D-->3C
3D-->22
3F-->19
3F-->1H
3F-->1L
3F-->1N
3F-->1Q
3F-->1U
3F-->2A
3F-->1G
3F-->3D
