flowchart LR

0[".dependency-cruiser.js"]
subgraph 1["application"]
subgraph 2["boardgame"]
3["AddBoardGameToUser.ts"]
4["FindBoardGame.ts"]
5["GetUserGameCollection.ts"]
end
subgraph 6["user"]
7["ChangeNickname.ts"]
8["CreateUser.ts"]
C["ValidateNickname.ts"]
end
end
subgraph 9["domain"]
A["User.ts"]
M["BoardGame.ts"]
T["Friendship.ts"]
U["Group.ts"]
V["Location.ts"]
W["Session.ts"]
X["SessionPlayer.ts"]
Y["UserBoardGames.ts"]
end
B["crypto"]
subgraph D["composition"]
E["boardGame.ts"]
Q["user.ts"]
end
subgraph F[".."]
subgraph G["application"]
subgraph H["boardgame"]
I["getUserGameCollection"]
end
end
end
subgraph J["infrastructure"]
subgraph K["postgres"]
L["BoardGameRepository.ts"]
P["db.ts"]
R["UserRepository.ts"]
18["SessionPlayerRepository.ts"]
19["SessionRepository.ts"]
end
subgraph Z["InMemory"]
10["BoardGameRepository.ts"]
13["SessionPlayerRepository.ts"]
15["SessionRepository.ts"]
17["UserRepository.ts"]
end
end
subgraph N["ports"]
O["BoardGameRepository.ts"]
S["UserRepository.ts"]
14["SessionPlayerRepository.ts"]
16["SessionRepository.ts"]
end
11["fs"]
12["path"]
subgraph 1A["interfaces"]
subgraph 1B["http"]
subgraph 1C["controllers"]
1D["addBoardGameToUserController.ts"]
1E["createUserController.ts"]
1F["findBoardGameController.ts"]
1G["getUserGameCollectionController.ts"]
1H["updateNicknameController.ts"]
1I["validateNicknameController.ts"]
end
subgraph 1J["routes"]
1K["boardgames.ts"]
1L["users.ts"]
end
1M["server.ts"]
end
end
1N["server.ts"]
subgraph 1O["tests"]
1P["dbTest.js"]
end
8-->A
A-->B
E-->3
E-->4
E-->I
E-->L
E-->P
L-->M
L-->O
Q-->7
Q-->8
Q-->C
Q-->P
Q-->R
R-->A
R-->S
10-->O
10-->11
10-->12
13-->14
15-->16
17-->V
17-->A
17-->S
18-->X
18-->14
19-->W
19-->16
1K-->1D
1K-->1F
1K-->1G
1L-->1E
1L-->1H
1L-->1I
1M-->1K
1M-->1L
1N-->E
1N-->Q
1N-->P
1N-->1M
