flowchart LR

0[".dependency-cruiser.js"]
subgraph 1["application"]
subgraph 2["boardgame"]
3["AddBoardGameToUser.ts"]
4["DeleteBoardGame.ts"]
5["FindBoardGame.ts"]
6["GetUserGameCollection.ts"]
end
subgraph 7["friendships"]
8["AcceptRequest.ts"]
9["AddFriend.ts"]
A["DeclineRequest.ts"]
B["GetFriendRequests.ts"]
C["GetFriends.ts"]
D["InviteFriend.ts"]
end
subgraph E["location"]
F["CreateLocation.ts"]
I["FindLocationById.ts"]
end
subgraph J["session"]
K["AddLocationToSession.ts"]
M["CreateSession.ts"]
N["GetGameSessions.ts"]
O["GetSessionById.ts"]
P["GetSessionsByUserId.ts"]
Q["findByGroupID.ts"]
R["updateSession.ts"]
end
subgraph S["sessionPlayer"]
T["findBySessionAndUser.ts"]
U["findBySessionID.ts"]
V["findByUserID.ts"]
W["saveSessionPlayer.ts"]
end
subgraph X["user"]
Y["AddAvatar.ts"]
Z["AddFavoriteLocation.ts"]
10["ChangeNickname.ts"]
11["CreateUser.ts"]
13["DeleteUser.ts"]
14["FetchUserNickname.ts"]
15["GetFavoriteLocations.ts"]
16["ValidateNickname.ts"]
end
end
subgraph G["domain"]
H["Location.ts"]
L["Session.ts"]
12["User.ts"]
1C["BoardGame.ts"]
1I["Friendship.ts"]
1R["SessionPlayer.ts"]
1W["Group.ts"]
1X["UserBoardGames.ts"]
end
subgraph 17["composition"]
18["boardGame.ts"]
1G["friendships.ts"]
1K["location.ts"]
1M["session.ts"]
1P["sessionPlayer.ts"]
1T["user.ts"]
end
subgraph 19["infrastructure"]
subgraph 1A["postgres"]
1B["BoardGameRepository.ts"]
1F["db.ts"]
1H["FriendRepository.ts"]
1L["LocationRepository.ts"]
1N["SessionRepository.ts"]
1Q["SessionPlayerRepository.ts"]
1U["UserRepository.ts"]
end
subgraph 1Y["InMemory"]
1Z["BoardGameRepository.ts"]
22["FriendRepository.ts"]
23["LocationRepository.ts"]
24["SessionPlayerRepository.ts"]
25["SessionRepository.ts"]
26["UserRepository.ts"]
end
subgraph 27["bgg"]
28["BggXmlApi2Client.ts"]
29["bggSyncWorker.ts"]
end
end
subgraph 1D["ports"]
1E["BoardGameRepository.ts"]
1J["FriendRepository.ts"]
1O["SessionRepository.ts"]
1S["SessionPlayerRepository.ts"]
1V["UserRepository.ts"]
3C["LocationRepository.ts"]
end
20["fs"]
21["path"]
subgraph 2A["interfaces"]
subgraph 2B["http"]
subgraph 2C["controllers"]
2D["acceptRequestController.ts"]
2E["addAvatarController.ts"]
2F["addBoardGameToUserController.ts"]
2G["addFavoriteLocationController.ts"]
2H["addFriendController.ts"]
2I["addLocationToSessionController.ts"]
2J["createSessionController.ts"]
2K["createUserController.ts"]
2L["declineFriendRequestController.ts"]
2M["deleteBoardGameController.ts"]
2N["deleteUserController.ts"]
2O["fetchUserNicknameController.ts"]
2P["findBoardGameController.ts"]
2Q["getFavoriteLocationsController.ts"]
2R["getFriendRequestsController.ts"]
2S["getFriendsController.ts"]
2T["getSessionByIdController.ts"]
2U["getSessionController.ts"]
2V["getSessionsByUserIdController.ts"]
2W["getUserGameCollectionController.ts"]
2X["inviteFriendController.ts"]
2Y["saveSessionPlayerController.ts"]
2Z["updateNicknameController.ts"]
30["updateSessionController.ts"]
31["validateNicknameController.ts"]
end
subgraph 32["middleware"]
33["auth.ts"]
34["uploadAvatar.ts"]
end
subgraph 35["routes"]
36["boardgames.ts"]
37["friendships.ts"]
38["sessionPlayers.ts"]
39["sessions.ts"]
3A["users.ts"]
end
3B["server.ts"]
end
end
3D["server.ts"]
subgraph 3E["tests"]
3F["dbTest.js"]
end
F-->H
K-->H
K-->L
M-->H
M-->L
R-->L
11-->12
18-->3
18-->4
18-->5
18-->6
18-->1B
18-->1F
1B-->1C
1B-->1E
1G-->8
1G-->9
1G-->A
1G-->B
1G-->C
1G-->D
1G-->1F
1G-->1H
1H-->1I
1H-->1J
1K-->F
1K-->I
1K-->1F
1K-->1L
1L-->H
1M-->K
1M-->M
1M-->N
1M-->O
1M-->P
1M-->R
1M-->1F
1M-->1L
1M-->1N
1N-->L
1N-->1O
1P-->T
1P-->U
1P-->V
1P-->W
1P-->1F
1P-->1Q
1Q-->1R
1Q-->1S
1T-->Y
1T-->Z
1T-->10
1T-->11
1T-->13
1T-->14
1T-->15
1T-->16
1T-->1F
1T-->1U
1U-->H
1U-->12
1U-->1V
1Z-->1E
1Z-->20
1Z-->21
23-->H
24-->1S
25-->1O
26-->H
26-->12
26-->1V
29-->28
2E-->20
2E-->21
34-->20
34-->21
36-->2F
36-->2M
36-->2P
36-->2W
36-->33
37-->2D
37-->2H
37-->2L
37-->2R
37-->2S
37-->2X
37-->33
38-->2Y
39-->2I
39-->2J
39-->2T
39-->2U
39-->2V
39-->30
39-->33
3A-->2E
3A-->2G
3A-->2K
3A-->2N
3A-->2O
3A-->2Q
3A-->2Z
3A-->31
3A-->33
3B-->33
3B-->36
3B-->37
3B-->38
3B-->39
3B-->3A
3B-->21
3D-->18
3D-->1G
3D-->1K
3D-->1M
3D-->1P
3D-->1T
3D-->29
3D-->1F
3D-->3B
